### ISSUE TITLE
easy-trivia functions not working

### ISSUE THREAD

**Issue by ozair-dev** [Elitezen/easy-trivia#12]
I appreciate the effort you put in making this wrapper but the functions are not working at all.
E.g, the code
```
import React, {useEffect } from "react";
import { getQuestions } from 'easy-trivia';
import "./App.css";

function App() {

  useEffect(async ()=>{
    const questions = await getQuestions({
      amount: 50,
      difficulty: 'easy',
      type: 'multiple',
      category: 'history'
    });
    console.log(questions)

  })

  return <div className="App"></div>;
}

export default App;
```
gives the error
```
Uncaught (in promise) TypeError: get is not a function
    at private.js:164
    at new Promise (<anonymous>)
    at _request (private.js:162)
    at getQuestions (public.js:60)
    at App.jsx:9
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
```

And the code 
```
import React, {useEffect } from "react";
import { Categories } from 'easy-trivia';
import "./App.css";

function App() {

  useEffect(async ()=>{
    const categoryData = await Categories.getCategoryDat('GENERAL_KNOWLEDGE');
    console.log(categoryData);

  })

  return <div className="App"></div>;
}

export default App;
```
gives the error
```
Uncaught (in promise) TypeError: Categories.getCategoryDat is not a function
    at App.jsx:9
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushPassiveEffects (react-dom.development.js:23447)
    at react-dom.development.js:23324
(anonymous) @ App.jsx:9
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
(anonymous) @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
```
Is it still **work in progress**? Or there is something wrong from my end?

**Comment by ozair-dev** [comment]
using **vitejs** as build tool

**Comment by Elitezen** [comment]
For the second error, the function is `.getCategoryData()` with an `a` at the end. As for the first, I'm unsure why `get` is returning undefined though it is being imported from the https module. Which NodeJS version are you running?

Thanks for bringing this to my attention.

**Comment by ozair-dev** [comment]
Sorry I didn't notice the typo in second code (same typo in the readme file).
I now see that i need to use node version >= 16,
I am changing node version using nvm, and also downloading **node** locally in the project but the erros persists.
It works fine in VanillaJs code. Error occus only when i run project with npm. I think that the project is not using the proper node version but I dunno why.

**Comment by ozair-dev** [comment]
I found out that it is not the problem in your code. As **http** is a **node module** and it needs to be polyfilled in the browser enviroment. Webpack automatically polyfills it. But vite doesn't. So, it has to be done manually.

**Comment by Elitezen** [comment]
I apologize for the typo. Seems like this was an environment issue then. I'll now close this issue.

**Comment by Niputi** [comment]
Hello @Elitezen according to your readme, you claim to be esm compliant but your package does not provide any esm version and uses a node builtin module at https://github.com/Elitezen/easy-trivia/blob/main/src/functions/private.js#L6 which is not esm compliant. 
if you want to make your package esm compliant, I would recommend https://github.com/unjs/ohmyfetch for the fetch mechanism and using rollup to provide esm/commonjs output where esm output is ending with the extension `.mjs`

**Comment by Niputi** [comment]
if this is something you want a helping hand in, I can take a look at it
